name: 'Deploy to Cloud Run from Source'

on:
  workflow_dispatch:
    # Optional: Define inputs if you want to provide parameters when triggering manually
    inputs:
      my_input:
        description: 'A custom input'
        required: false
        default: 'default_value'
  push:
    branches:
      - '"main"'
      
env:
  PROJECT_ID: "ac-2025-8-15"
  POOL_ID: "github-pool"
  PROVIDER_ID: "github-provider"
  SERVICE_ACCOUNT: "github-sa@ac-2025-8-15.iam.gserviceaccount.com"
  GITHUB_REPO: "AC740/cloudrun"
  PROJECT_NUMBER: "196200699792"


jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332' # actions/checkout@v4

      - id: 'auth'
        name: 'Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/${{PROJECT_NUMBER}}/locations/global/workloadIdentityPools/${{POOL_ID}}/providers/github-actions-provider-console'
          service_account: '${{ env.SERVICE_ACCOUNT_EMAIL }}'
          
      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@33553064113a37d688aa6937bacbdc481580be17' # google-github-actions/deploy-cloudrun@v2
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          # NOTE: If using a different source folder, update the image name below:
          source: './'

      # If required, use the Cloud Run URL output in later steps
      - name: 'Show output'
        run: |-
          echo ${{ steps.deploy.outputs.url }}
