name: 'Build and Deploy to Cloud Run'

on:
  workflow_dispatch:
    # Optional: Define inputs if you want to provide parameters when triggering manually
    inputs:
      my_input:
        description: 'A custom input'
        required: false
        default: 'default_value'
  push:
    branches:
      - 'main'

permissions:
  id-token: write
  contents: read

env:
  PROJECT_ID: "ac-2025-8-15"
  # Use the clean service account we created
  SERVICE_ACCOUNT: "github-deploy-sa@ac-2025-8-15.iam.gserviceaccount.com"
  REGION: "us-central1"
  SERVICE: "my-service"
  # The Artifact Registry repo you just created
  ARTIFACT_REPO: "cloudrun-repo"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/196200699792/locations/global/workloadIdentityPools/github-pool/providers/github-actions-provider-console'
          service_account: '${{ env.SERVICE_ACCOUNT }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Build and Push Docker Image'
        run: |-
          # This builds your Dockerfile and pushes the container to Artifact Registry
          gcloud builds submit --tag ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/${{ env.SERVICE }}

      - name: 'Deploy to Cloud Run'
        run: |-
          # This deploys the specific image you just built
          gcloud run deploy ${{ env.SERVICE }} \
            --image ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/${{ env.SERVICE }} \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated
