name: 'Deploy to Cloud Run from Source'

on:
  workflow_dispatch:
    # Optional: Define inputs if you want to provide parameters when triggering manually
    inputs:
      my_input:
        description: 'A custom input'
        required: false
        default: 'default_value'
  push:
    branches:
      - '"main"'

env:
  PROJECT_ID: ac-2025-8-15
  REGION: us-central1
  SERVICE_ACCOUNT_EMAIL: github-sa@ac-2025-8-15.iam.gserviceaccount.com
  SERVICE: my-service

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332' # actions/checkout@v4

      - id: 'auth'
        name: 'Google Cloud'
        uses: 'google-github-actions/auth@f112390a2df9932162083945e46d439060d66ec2' # google-github-actions/auth@v2
        with: 
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      # workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider' # TODO: replace with your workload identity provider

      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@33553064113a37d688aa6937bacbdc481580be17' # google-github-actions/deploy-cloudrun@v2
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          # NOTE: If using a different source folder, update the image name below:
          source: './'

      # If required, use the Cloud Run URL output in later steps
      - name: 'Show output'
        run: |-
          echo ${{ steps.deploy.outputs.url }}
